services:
  - type: web
    name: attendance-system
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: attendance-db
          property: connectionString
    autoDeploy: true
    healthCheckPath: /health
    # Ensure the database is ready before starting the service
    dependencies:
      - name: attendance-db

databases:
  - name: attendance-db
    databaseName: attendance
    plan: free
    ipAllowList: [] # only allow internal connections
